### ISSUE TITLE
Compilation Error on Unix: "Multiple definitions"

### ISSUE THREAD

**Issue by hansbonini** [lab313ru/gpgx_debugger#2]
Compilation error when try to compile new release under Unix system:

```
/usr/bin/ld: CMakeFiles/gpgx_debugger.dir/libretro/libretro.c.o:(.bss+0xe0): multiples definitions of "config"; CMakeFiles/gpgx_debugger.dir/core/system.c.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/gpgx_debugger.dir/build.make:1634: libgpgx_debugger.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/gpgx_debugger.dir/all] Error 2
make: *** [Makefile:104: all] Error 2
```

System:
```
Linux akuma 5.4.44-1-MANJARO #1 SMP PREEMPT Wed Jun 3 14:48:07 UTC 2020 x86_64 GNU/Linux
```

Solved renaming variable in core/system.c:
```
t_config config
```
to:
```
t_config gpgx_config
```

**Comment by lab313ru** [comment]
Not tested on Linux (there is no gui for Linux here yet). Anyway, I'm 
creating a new crossplatform gui for the debugger. So, please wait for it.

Hans Bonini <notifications@github.com> 17 июля 2020 г. 23:24:16 написал:

**Comment by hansbonini** [comment]
I'm very glad to know about this. Is this new gui QT-based?

**Comment by lab313ru** [comment]
Maybe. Cause Retroarch gui is Qt based too. But it's a problem to join its 
events loop, as I remember.

Hans Bonini <notifications@github.com> 19 июля 2020 г. 05:54:21 написал:

**Comment by hansbonini** [comment]
Did you take a look on LibRetroReversing project?

**Comment by lab313ru** [comment]
Now - yes.:)
